version: '3.8'

services:
  zharchiver:
    # 自动拉取 GitHub Actions 在云端为您打包好的最新镜像，彻底告别 VPS 上的卡顿编译！
    image: ghcr.io/hhlli/zharchiver:latest
    container_name: zharchiver
    restart: unless-stopped
    ports:
      # 将主机的 8080 端口映射到容器的 8080 端口
      - "8080:8080"
    volumes:
      # 持久化 SQLite 数据库文件目录，防止 WAL 数据丢失
      - ./data/db:/app/db
      # 持久化抓取下来的图片等静态资源
      - ./data/storage:/app/storage
    environment:
      # 如果需要，可以在这里设置环境变量
      - TZ=Asia/Shanghai
